# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bookyt_projects"
  s.version = "0.6.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Simecek"]
  s.date = "2011-10-12"
  s.description = "Rails engine for project management it's used to extend the functionallity of bookyt."
  s.email = "roman.simecek@cyt.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/stylesheets/bookyt_projects.sass",
    "app/controllers/activities_controller.rb",
    "app/controllers/project_states_controller.rb",
    "app/controllers/projects_controller.rb",
    "app/models/activity.rb",
    "app/models/project.rb",
    "app/models/project_state.rb",
    "app/views/activities/_form.html.haml",
    "app/views/activities/_resource_detail.html.haml",
    "app/views/activities/show.html.haml",
    "app/views/project_states/_form.html.haml",
    "app/views/project_states/new.html.haml",
    "app/views/projects/_form.html.haml",
    "app/views/projects/_list.html.haml",
    "app/views/projects/_resource_detail.html.haml",
    "app/views/projects/new.html.haml",
    "app/views/projects/show.html.haml",
    "bookyt_projects.gemspec",
    "config/application.rb",
    "config/boot.rb",
    "config/locales/de.yml",
    "config/routes.rb",
    "lib/bookyt_projects.rb",
    "lib/bookyt_projects/navigation.rb",
    "lib/bookyt_projects/railtie.rb",
    "script/cucumber",
    "script/rails",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/raskhadafi/bookyt_projects"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Rails engine for project management"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.6"])
    else
      s.add_dependency(%q<rails>, ["~> 3.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.6"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.6"])
  end
end

