# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bookyt_projects}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Roman Simecek}]
  s.date = %q{2011-09-19}
  s.description = %q{Rails engine for project management it's used to extend the functionallity of bookyt.}
  s.email = %q{roman.simecek@cyt.ch}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/stylesheets/bookyt_projects.sass",
    "app/controllers/project_states_controller.rb",
    "app/controllers/projects_controller.rb",
    "app/controllers/tasks_controller.rb",
    "app/models/project.rb",
    "app/models/project_state.rb",
    "app/models/task.rb",
    "app/views/project_states/_form.html.haml",
    "app/views/project_states/new.html.haml",
    "app/views/projects/_form.html.haml",
    "app/views/projects/_list.html.haml",
    "app/views/projects/_resource_detail.html.haml",
    "app/views/projects/new.html.haml",
    "app/views/projects/show.html.haml",
    "app/views/tasks/_form.html.haml",
    "bookyt_projects.gemspec",
    "config/locales/de.yml",
    "config/routes.rb",
    "lib/bookyt_projects.rb",
    "lib/bookyt_projects/navigation.rb",
    "lib/bookyt_projects/railtie.rb",
    "test/helper.rb",
    "test/test_bookyt_projects.rb"
  ]
  s.homepage = %q{http://github.com/raskhadafi/bookyt_projects}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Rails engine for project management}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.1.0.rc"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.1.0.rc"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.1.0.rc"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

